### ISSUE TITLE
Create a Sound Generator using Python 

### ISSUE THREAD

**Issue by PedroHTeixeira** [samsvp/Sound-Source-Localization#2]
As the MATLAB solution proved to be a very time-consuming process to create audio, we decided to try using python to create a sine waves and then shift them by the time delay.

**Comment by samsvp** [comment]
The sound generator has been developed using the time domain beamforming delays to simulate the way that the hydrophones would receive the audio.

**Comment by samsvp** [comment]
The ability to generate noise has been added.
